### ISSUE TITLE
Error message when selling item and buying it back

### ISSUE THREAD

**Issue by slackersink** [MJGT-Studio/MasterInventoryDocs#2]
Hi, I'm just checking out your asset now, and I got this error in the demo map. It was a freshly created project, v2.1.0.

I've tried a few times and get it each time. 
Pick up the berries, then head to the shop and sell 1. Don't exit the shop menu. Click buy, then buy the stack of 1 back. 

It only works when I buy the new stack of 1 after selling. If I sell a berry, then buy one from the stack of 5, I don't get the error. 

Blueprint Runtime Error: "Accessed None trying to read property K2Node_CustomEvent_playerInventory_1". Node:  Get Graph:  EventGraph Function:  Execute Ubergraph BP Master Inventory Blueprint:  BP_MasterInventory

**Comment by mariojgt** [comment]
Thanks i will look to it.

**Comment by mariojgt** [comment]
<img width="1143" alt="BugFix" src="https://user-images.githubusercontent.com/7347012/219503144-261f4937-5863-4ef8-b206-f201e8a1b783.png">

Just found the bug was just a quick check in the widgets inside the vendor ui in the BP_MasterInventory

The next minor release 2.2.1 will include the fix.
